---
- name: installing tomcat on ubuntu
  hosts: all
  become: yes
  tasks: 
    - name: installing the java 
      ansible.builtin.apt:
        name: openjdk-11-jdk
        update_cache: yes
        state: present